FROM node:latest as build-stage

WORKDIR /app

COPY pos-webapp-frontend/package*.json ./

RUN npm install

COPY pos-webapp-frontend/ .

RUN npm run build

FROM nginx:alpine

# Copy the build output to replace the default nginx contents.
COPY --from=build-stage /app/build /usr/share/nginx/html

COPY pos-webapp-frontend/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
